import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Window } from 'happy-dom';

for (const [lineEnding, newline] of [['LF', '\n'], ['CRLF', '\r\n']]) test(`the actual application UI switches transmissions, retains four strokes and operates guided energy scenarios (${lineEnding})`, async t => {
  const window = new Window({ url: 'http://localhost/Engine/' });
  const saved = new Map();
  for (const key of ['window', 'document', 'CustomEvent', 'ResizeObserver', 'requestAnimationFrame', 'cancelAnimationFrame']) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, writable: true, value: key === 'requestAnimationFrame' ? () => 0 : key === 'window' ? window : window[key] });
  }
  const errors = [];
  window.addEventListener('error', event => errors.push(event.error));
  window.document.body.innerHTML = '<div id="app"></div>';
  const originalError = console.error;
  let app;
  console.error = () => {};
  try {
    const source = (await readFile(new URL('../src/main.js', import.meta.url), 'utf8'))
      .replace(/\r?\n/g, newline)
      .replace(/^import ['"].*\.css['"];\r?\n/gm, '')
      .replace(/from '(\.\/[^']+)'/g, (_, path) => `from '${new URL(path, new URL('../src/main.js', import.meta.url)).href}'`);
    app = await import(`data:text/javascript;base64,${Buffer.from(source + '\nexport { sim, player, updateUI, choosePart, toastTimer };').toString('base64')}`);
    console.error = originalError;
    const $ = selector => window.document.querySelector(selector);
    const select = (selector, value) => { $(selector).value = value; $(selector).dispatchEvent(new window.Event('change', { bubbles: true })); };
    const input = (selector, value) => { $(selector).value = value; $(selector).dispatchEvent(new window.Event('input', { bubbles: true })); };
    const run = seconds => { app.sim.paused = false; for (let time = 0; time < seconds; time += 0.02) app.sim.update(0.02); app.updateUI(); };
    await t.test('render quality is selectable and help follows the actual transmission', () => {
      assert.equal($('#render-quality').value, 'auto');
      for (const quality of ['economy', 'high', 'auto']) select('#render-quality', quality);
      for (const [transmission, hint] of [['dct', /1–6/], ['automatic', /1–8/], ['hybrid', /D.*N.*P/], ['manual', /1–5/]]) {
        select('#transmission-type', transmission);
        assert.match($('#help-shortcuts').textContent, hint);
        if (transmission !== 'manual') assert.doesNotMatch($('.learning-strip p').textContent, /Wciśnij sprzęgło/);
      }
    });
    await t.test('telemetry refreshes a stroke hidden during suspension when the cycle panel returns', () => {
      $('.view-tab[data-view="suspension"]').click();
      app.sim.angle = 460; app.updateUI(true);
      $('.view-tab[data-view="engine"]').click();
      assert.match($('#stroke-description').textContent, /rozpręż|tłok/i);
      assert.equal($('#stroke-badge').textContent, '03');
      $('#reset').click();
      $('.view-tab[data-view="drive-detail"]').click();
    });
    await t.test('default whole vehicle, nine compact engine choices and manual clutch toggle remain available', () => {
      assert.ok($('.visual-panel').classList.contains('vehicle-mode'));
      assert.equal($('#cycle-panel').hidden, false);
      assert.equal(window.document.querySelectorAll('.engine-buttons [data-engine]').length, 9);
      assert.equal($('.engine-buttons [data-engine="boxer4"]'), null);
      $('#clutch-toggle').click(); assert.equal(app.sim.clutch, 1);
      $('#clutch-toggle').click(); assert.equal(app.sim.clutch, 0);
    });
    await t.test('the main navigation exposes suspension and keeps secondary mechanisms in drivetrain inspections', () => {
      const views = [...window.document.querySelectorAll('.view-tab')].map(button => button.dataset.view);
      assert.deepEqual(views, ['engine', 'cylinder', 'drive-detail', 'clutch', 'gearbox', 'differential', 'hybrid', 'suspension']);
      $('.view-tab[data-view="drive-detail"]').click();
      const sections = [...$('#inspect-section').options].map(option => option.value);
      for (const section of ['timing', 'oil', 'fuel', 'turbo']) {
        assert.ok(sections.includes(section), `${section} remains accessible from the complete drivetrain`);
        select('#inspect-section', section);
        assert.equal($('.visual-panel').dataset.inspection, section);
        $('#inspect-description').click();
        assert.equal($('#part-panel').hidden, false);
        assert.ok($('#part-description').textContent.trim().length > 20);
        $('#close-part').click();
      }
      select('#inspect-section', 'all');
      select('#car-preset', 'wrx-2024');
      assert.equal(app.sim.engineId, 'boxer4', 'the Subaru architecture remains supported by its car preset');
      assert.equal($('.engine-buttons [data-engine="boxer4"]'), null, 'a preset does not recreate the removed picker button');
      $('#reset').click();
    });
    await t.test('camera pan toggle and device choice expose their current behavior', () => {
      $('#camera-pan').click();
      assert.equal($('#camera-pan').getAttribute('aria-pressed'), 'true');
      assert.equal($('#scene').dataset.cameraPan, 'true');
      assert.match($('.orbit-hint').textContent, /Przeciągnij: przesuwanie/);
      select('#camera-input', 'mouse');
      assert.match($('.orbit-hint').textContent, /kółko: zoom/);
      select('#camera-input', 'touchpad');
      assert.match($('.orbit-hint').textContent, /2 palce: przesuwanie/);
      $('#camera-pan').click();
      assert.equal($('#scene').dataset.cameraPan, 'false');
    });
    await t.test('DCT removes the pedal, exposes six gears and prepares the opposite clutch', () => {
      select('#transmission-type', 'dct');
      assert.equal($('#clutch-control').hidden, true);
      assert.equal($('#quick-clutch-control').hidden, true);
      assert.equal($('#quick-gear').options.length, 7);
      $('[data-gear="1"]').click(); run(2);
      assert.equal(app.sim.gear, 1);
      assert.match($('#dct-state').textContent, /przygotowany 2/);
      assert.match($('#dct-k2').textContent, /0 Nm/);
      $('[data-gear="2"]').click();
      assert.match($('#mechanism-detail').textContent, /Wybierak ustawia nowy bieg/);
      $('#dct-shift-step').click();
      assert.equal(app.sim.shiftStage, 'handover');
      assert.match($('#mechanism-detail').textContent, /Oba pakiety przejmują napęd z poślizgiem/);
      assert.doesNotMatch($('#mechanism-detail').textContent, /ma otwarte sprzęgło/);
      $('#dct-shift-step').click();
      assert.match($('#mechanism-detail').textContent, /ustala docisk sprzęgła nowego biegu/);
      $('#dct-shift-step').click();
      assert.equal(app.sim.gear, 2);
    });
    await t.test('hybrid exposes battery, range and DC/AC directions with finite initial values', () => {
      select('#transmission-type', 'hybrid');
      assert.equal(app.sim.driveLayout, 'fwd');
      assert.equal($('#hybrid-controls').hidden, false);
      assert.equal($('.view-tab[data-view="clutch"]').textContent, 'Podział mocy');
      assert.equal($('.view-tab[data-view="gearbox"]').textContent, 'e-CVT');
      assert.equal($('#gear-control')?.hidden ?? $('.gear-control').hidden, true);
      assert.equal($('#quick-gear').options.length, 3);
      assert.ok(!$('#hybrid-controls').textContent.includes('NaN'));
      select('#vehicle-layer', 'electric');
      assert.match($('.scene-legend').textContent, /DC.*AC/s);
      input('#quick-throttle', '30'); run(2);
      assert.ok(app.sim.hybrid.batteryPower > 0);
      assert.equal($('#energy-battery').dataset.direction, 'forward');
      select('#hybrid-range', 'P'); assert.equal(app.sim.hybrid.range, 'D');
    });
    await t.test('custom mounting is visible above the model and configuration updates remain consistent', () => {
      select('#transmission-type', 'manual');
      assert.equal($('#mount-settings').contains($('#drive-layout')), true);
      assert.equal($('#mount-settings').contains($('#engine-orientation')), true);
      assert.equal($('#mount-settings').hidden, false);
      select('#engine-orientation', 'transverse');
      assert.equal(app.sim.driveLayout, 'fwd');
      assert.equal($('#drive-layout').value, 'fwd');
      select('#drive-layout', 'rwd');
      assert.equal(app.sim.engineOrientation, 'longitudinal');
      assert.equal($('#engine-orientation').value, 'longitudinal');
    });
    await t.test('head inspection and a partial-clutch launch explain force, slip and disconnection', () => {
      select('#transmission-type', 'manual');
      $('.view-tab[data-view="engine"]').click();
      assert.ok([...$('#inspect-section').options].some(option => option.value === 'cylinderHead'));
      $('#show-head').click();
      assert.equal($('#inspect-section').value, 'cylinderHead');
      assert.equal($('#isolate').checked, true);
      assert.match($('#part-description').textContent, /zawor|kanał/);
      $('.view-tab[data-view="clutch"]').click();
      assert.equal($('#isolate-option').hidden, false);
      assert.equal($('#show-head').hidden, true);
      assert.equal($('#explode').value, '0');
      assert.equal($('#clutch-display').dataset.state, 'assembled');
      assert.equal($('#clutch-clamp-value').textContent, '100%');
      assert.equal($('#clutch-status').hidden, false, 'the friction state is visible beside the mechanism');
      assert.equal($('#clutch-schematic').open, false, 'the extra schematic does not fill the default toolbar');
      Object.assign(app.sim, { paused: true, rpm: 1400, inputOmega: 1400 * Math.PI / 30, transmittedTorque: 22, clutchSlip: 900, gear: 1 });
      $('[data-clutch-pedal="0.5"]').click();
      assert.equal($('#clutch-status').dataset.state, 'grip', 'half pedal with synchronous speeds does not imply sliding, even with stale telemetry');
      assert.equal($('#clutch-engine-rpm').textContent, $('#clutch-input-rpm').textContent);
      assert.match($('#drive-status').textContent, /obroty wyrównane/, 'the main drive status uses the same actual speeds');
      assert.match($('#clutch-mechanism-detail').textContent, /hydraulika.*łożysko.*sprężyny/);
      $('[data-clutch-pedal="1"]').click();
      assert.equal(app.sim.clutch, 1);
      assert.equal($('#clutch-clamp-value').textContent, '0%');
      assert.equal($('#clutch-status').dataset.state, 'open');
      assert.match($('#clutch-gap-state').textContent, /szczelin/i);
      assert.match($('#contact-detail').textContent, /przenoszone 0 Nm.*ciepło 0\.00 kW/);
      $('[data-clutch-pedal="0"]').click();
      assert.equal($('#diagram-pressure').getAttribute('x'), '102');
      assert.equal($('#clutch-clamp-value').textContent, '100%');
      assert.equal($('#mechanism-readout').hidden, true);
      $('#show-readout').click();
      assert.equal($('#mechanism-readout').hidden, false);
      $('#mechanism-readout .close-readout').click();
      $('#spread-clutch').click();
      assert.equal($('#explode').value, '70');
      assert.equal($('#clutch-status').dataset.state, 'exploded');
      assert.match($('#contact-state').textContent, /MONTAŻOWE/);
      assert.equal($('#diagram-torque').style.opacity, '0');
      $('.view-tab[data-view="drive-detail"]').click();
      select('#inspect-section', 'clutch'); app.updateUI();
      assert.equal($('#clutch-status').hidden, true, 'whole-vehicle inspection keeps its existing readout without an overlapping bench card');
      assert.equal($('#clutch-display').dataset.state, 'assembled', 'the vehicle uses the assembled clutch');
      assert.equal($('#assemble-clutch').disabled, true);
      $('.view-tab[data-view="clutch"]').click();
      assert.equal($('#explode').value, '70', 'the bench remembers the selected exploded layout');
      $('#assemble-clutch').click();
      assert.equal($('#explode').value, '0');
      $('.view-tab[data-view="engine"]').click();
      $('.view-tab[data-view="clutch"]').click();
      assert.equal($('#explode').value, '0', 'the chosen assembled layout survives a tab change');
      $('#clutch-slip-demo').click(); run(0.08);
      assert.equal(app.sim.gear, 1);
      assert.equal(app.sim.clutch, 0.5);
      assert.ok(app.sim.clutchSlip > 60);
      assert.ok(app.sim.slipPower > 0);
      assert.equal($('#clutch-status').dataset.state, 'slip');
      assert.notEqual($('#clutch-engine-rpm').textContent, $('#clutch-input-rpm').textContent);
      assert.match($('#clutch-motion').textContent, /Różnica obrotów.*ciepło/);
      assert.match($('#contact-detail').textContent, /Docisk.*poślizg.*ciepło/i);
      input('#quick-clutch', '80'); run(0.08);
      assert.equal(app.sim.transmittedTorque, 0);
      assert.match($('#drive-status').textContent, /rozłączone/);
      assert.equal($('#clutch-status').dataset.state, 'open');
      assert.match($('#mechanism-state').textContent, /brak zacisku/);
      $('.view-tab[data-view="gearbox"]').click();
      select('#inspect-section', 'gear2'); app.updateUI();
      assert.match($('#shift-detail').textContent, /Koło biegu 2 obraca się swobodnie.*Bieg 1 jest włączony/);
      assert.equal($('[data-shift-stage="idle"]').classList.contains('active'), false);
      $('.view-tab[data-view="clutch"]').click();
      $('#spread-clutch').click();
      $('#reset').click();
      $('.view-tab[data-view="clutch"]').click();
      assert.equal($('#explode').value, '0', 'reset restores the assembled working view');
    });
    await t.test('8AT hides the clutch, exposes eight gears and converter inspections', () => {
      $('.view-tab[data-view="hybrid"]').click();
      select('#transmission-type', 'automatic');
      assert.equal(app.sim.transmission, 'automatic', 'changing transmission leaves the hybrid-only view');
      select('#car-preset', '508-eat8-2018');
      assert.equal(app.sim.transmission, 'automatic');
      assert.equal(app.sim.engineOrientation, 'transverse');
      assert.equal(app.sim.driveLayout, 'fwd');
      assert.equal($('#quick-gear').options.length, 9);
      assert.equal($('#clutch-control').hidden, true);
      assert.equal($('#automatic-auto-option').hidden, false);
      $('.view-tab[data-view="clutch"]').click();
      assert.match($('.view-tab[data-view="clutch"]').textContent, /Konwerter/);
      assert.ok([...$('#inspect-section').options].some(option => option.value === 'stator'));
      $('#automatic-auto').checked = false;
      $('#automatic-auto').dispatchEvent(new window.Event('change', { bubbles: true }));
      $('[data-gear="8"]').click(); run(1.3);
      assert.equal(app.sim.gear, 8);
      assert.match($('#automatic-state').textContent, /Bieg 8/);
    });
    await t.test('911 and Corolla presets keep their real architecture and custom changes clear the preset', () => {
      select('#car-preset', '911-carrera-s-2025');
      assert.equal(app.sim.engineId, 'boxer6');
      assert.equal(app.sim.enginePlacement, 'rear');
      assert.equal($('#car-preset').value, '911-carrera-s-2025');
      select('#engine-placement', 'mid');
      assert.equal($('#car-preset').value, '');
      select('#car-preset', 'corolla-hybrid-2025');
      assert.equal(app.sim.transmission, 'hybrid');
      assert.equal(app.sim.engineOrientation, 'transverse');
      assert.equal(app.sim.engineId, 'r4');
    });
    await t.test('Ibiza preset and whole FWD differential expose cornering controls', () => {
      select('#car-preset', 'ibiza-mpi-2016');
      assert.equal(app.sim.engineId, 'r3');
      assert.equal(app.sim.transmission, 'manual');
      assert.equal(app.sim.driveLayout, 'fwd');
      select('#inspect-section', 'differential');
      assert.equal($('#diff-lesson').hidden, false);
      assert.equal($('#diff-demo').hidden, false);
      assert.match($('.scene-legend').textContent, /Lewa półoś.*Prawa półoś.*Satelity/);
      $('[data-turn="1"]').click();
      assert.equal(app.sim.turn, 1);
      assert.match($('#diff-detail').textContent, /mechanicznie.*satelity.*jedna półoś/s);
      $('[data-turn="0"]').click();
      assert.match($('#diff-detail').textContent, /bez obrotu na własnych osiach/);
      select('#car-preset', 'corolla-hybrid-2025');
    });
    await t.test('regeneration reverses the battery arrow and its guided scenario reaches the full-battery step', () => {
      select('#scenario-select', 'regen'); $('#scenario-start').click();
      assert.equal(app.sim.paused, true);
      assert.equal(app.player.id, 'regen');
      $('#scenario-next').click();
      assert.ok(app.sim.hybrid.batteryPower < 0);
      assert.equal($('#energy-battery').dataset.direction, 'reverse');
      $('#scenario-next').click();
      assert.equal(app.sim.hybrid.soc, 0.85);
      assert.equal($('#energy-battery').dataset.active, 'false');
    });
    await t.test('4WD selector enforces stopped low-range changes and reset restores the original configuration', () => {
      select('#transmission-type', 'manual'); select('#drive-layout', 'partTime');
      assert.equal($('#transfer-mode-option').hidden, false);
      select('#transfer-mode', '4L'); assert.equal(app.sim.transferRatio, 2.5);
      app.sim.speed = 5; select('#transfer-mode', '4H'); assert.equal(app.sim.driveMode, '4L');
      $('#reset').click();
      assert.equal(app.sim.transmission, 'manual');
      assert.equal(app.sim.driveLayout, 'rwd');
      assert.equal($('#cycle-panel').hidden, false);
      assert.equal($('#hybrid-controls').hidden, true);
    });
    await t.test('synchronizer lesson pauses real shifting at cone contact then dog engagement', () => {
      $('.view-tab[data-view="gearbox"]').click();
      select('#synchronizer-gear', '3');
      $('#synchronizer-demo').click();
      assert.equal(app.sim.shiftTarget, 3);
      assert.equal(app.sim.clutch, 1);
      assert.equal(app.sim.paused, true);
      assert.equal($('#inspect-section').value, 'synchronizer');
      assert.equal($('#synchronizer-gear').disabled, true);
      $('#shift-step').click();
      assert.equal(app.sim.shiftStage, 'synchronize');
      assert.match($('#shift-detail').textContent, /pierścień|Pierścień/);
      $('#shift-step').click();
      assert.equal(app.sim.shiftStage, 'engage');
      $('#shift-step').click();
      assert.equal(app.sim.gear, 3);
      assert.equal(app.sim.shiftTarget, null);
      assert.equal($('#synchronizer-gear').disabled, false);
    });
    await t.test('suspension tab owns its road controls, pause and step without changing the car preset', () => {
      select('#car-preset', 'ibiza-mpi-2016');
      $('.view-tab[data-view="suspension"]').click();
      assert.equal(app.sim.suspensionActive, true);
      assert.equal($('#cycle-panel').hidden, true);
      assert.equal($('#suspension-controls').hidden, false);
      assert.equal($('.control-panel').hidden, true);
      select('#suspension-type', 'pullrod');
      assert.ok($('#inspect-section').querySelector('option[value="suspensionRocker"]'), 'push/pull linkage has a reachable close-up');
      assert.ok($('#inspect-section').querySelector('option[value="suspensionBody"]'), 'body attachment close-up is available');
      $('#labels').checked = false;
      $('#labels').dispatchEvent(new window.Event('change', { bubbles: true }));
      app.choosePart('suspensionDamper');
      assert.equal($('#part-panel').hidden, false);
      assert.equal($('#part-title').textContent, 'Amortyzator');
      assert.equal($('#labels').checked, false, 'part descriptions work without enabling canvas labels');
      assert.ok($('#part-description').textContent.length < 190, 'the selected part has a short explanation');
      app.choosePart('suspensionRocker');
      assert.match($('#part-description').textContent, /ciągnie drążek/);
      select('#suspension-type', 'pushrod');
      assert.match($('#part-description').textContent, /pcha drążek/);
      select('#suspension-type', 'leaf');
      assert.equal($('#inspect-section').querySelector('option[value="suspensionRocker"]'), null, 'inactive linkage inspection is removed');
      assert.equal($('#part-panel').hidden, true, 'a rocker description closes when that part disappears');
      app.choosePart('suspensionSpring');
      assert.equal($('#part-title').textContent, 'Resor piórowy');
      select('#suspension-type', 'pullrod');
      assert.equal($('#part-title').textContent, 'Sprężyna', 'an open description updates with the chosen layout');
      $('#close-part').click();
      $('#labels').checked = true;
      $('#labels').dispatchEvent(new window.Event('change', { bubbles: true }));
      select('#suspension-road', 'split');
      input('#suspension-amplitude', '12');
      input('#suspension-damping', '0');
      const engineAngle = app.sim.angle;
      run(1.1);
      assert.equal(app.sim.angle, engineAngle);
      assert.ok(app.sim.suspension.distance > 0);
      assert.equal(app.sim.suspension.type, 'pullrod');
      assert.equal(app.sim.suspension.damping, 0);
      assert.equal(app.sim.suspension.amplitude, 0.12);
      assert.equal($('#car-preset').value, 'ibiza-mpi-2016');
      $('#pause').click();
      const time = app.sim.suspension.time;
      app.sim.update(0.1);
      assert.equal(app.sim.suspension.time, time);
      $('#suspension-step').click();
      assert.ok(app.sim.suspension.time > time);
      assert.equal(app.sim.paused, true);
      $('#suspension-reset').click();
      assert.equal(app.sim.suspension.distance, 0);
      $('.view-tab[data-view="drive-detail"]').click();
      assert.equal(app.sim.suspensionActive, false);
      assert.equal($('#cycle-panel').hidden, false);
      assert.equal($('.control-panel').hidden, false);
      assert.equal($('#mount-settings').hidden, false);
      assert.equal(app.sim.engineId, 'r3');
    });
    await t.test('a repeated visible telemetry update makes no DOM mutations', () => {
      select('#transmission-type', 'manual');
      $('.view-tab[data-view="gearbox"]').click();
      $('#show-readout').click();
      app.sim.paused = true; app.updateUI(true);
      const observer = new window.MutationObserver(() => {});
      observer.observe($('#app'), { subtree: true, attributes: true, childList: true, characterData: true });
      app.updateUI(true);
      const records = observer.takeRecords(); observer.disconnect();
      assert.deepEqual(records.map(record => `${record.target.id}:${record.attributeName || record.type}`), []);
    });
    assert.deepEqual(errors, []);
    const ids = [...window.document.querySelectorAll('[id]')].map(node => node.id);
    assert.equal(new Set(ids).size, ids.length);
  } finally {
    console.error = originalError;
    clearTimeout(app?.toastTimer);
    await window.happyDOM.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else delete globalThis[key];
    }
  }
});
